version: '3'

services:

  in_api:
    build:
        context: ./platform_in/
        dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5002 manage:app
    #restart: always
    #volumes:
    #  - ./platform_in/:/project/
    expose:
      - 5002
    env_file:
      - config.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - in_api
